services:
  log-database:
    container_name: log-database
    image: postgres:14.4
    environment:
      - POSTGRES_USER=${USER_NAME}
      - POSTGRES_PASSWORD=${USER_NAME}
      - POSTGRES_DB=log-database
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./database/tables.sql:/docker-entrypoint-initdb.d/tables.sql

  log-api:
    depends_on:
      - log-database
    container_name: log-api
    image: log-api
    user: ${USER_NAME}
    hostname: docker
    working_dir: ${WORK_DIR}
    entrypoint: ["poetry", "run"]
    command: ["uvicorn", "source.__main__:log_api", "--host", "${API_HOST}", "--port", "${API_PORT}", "--reload"]
    ports:
      - ${API_PORT}:${API_PORT}
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USER_NAME: ${USER_NAME}
        WORK_DIR: ${WORK_DIR}
    volumes:
      - type: bind
        source: ./
        target: ${WORK_DIR}/
      - ${WORK_DIR}/.venv
