CREATE TABLE "USER" (
  "USER_ID" SERIAL NOT NULL,
  "USER_EMAIL" varchar(255),
  "USER_HASHED_PASSWORD" varchar,
  PRIMARY KEY ("USER_ID"),
  CONSTRAINT "UNIQUE_USER_EMAIL" UNIQUE ("USER_EMAIL")
);

CREATE TABLE "CUSTOMER" (
  "CUSTOMER_ID" SERIAL NOT NULL,
  "CUSTOMER_NAME" varchar(255),
  "CUSTOMER_EMAIL" varchar(255),
  "CUSTOMER_IS_ACTIVE" boolean,
  PRIMARY KEY ("CUSTOMER_ID"),
  CONSTRAINT "UNIQUE_CUSTOMER_EMAIL" UNIQUE ("CUSTOMER_EMAIL")
);

CREATE TABLE "EVENT" (
  "EVENT_ID" SERIAL NOT NULL,
  "CUSTOMER_ID" int,
  "EVENT_TYPE" varchar(255),
  "EVENT_REGISTERED_AT" timestamp,
  PRIMARY KEY ("EVENT_ID"),
  CONSTRAINT "FK_CUSTOMER_EVENT" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMER" ("CUSTOMER_ID")
);
